AllCops:
  TargetRubyVersion: 2.3
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Metrics/LineLength:
  Max: 120
